# TODO: Переделать получение пароля из файла
version: "3.6"

networks:
  net0:

services:
  
  openwrt:
    build:
      context: .
      dockerfile: ./openwrt-server/Dockerfile
      args:
        - root_passwd=1234
      target: openwrt
    ports:
      - 80:80
      - 443:443
      - 7681:7681
    networks:
      - net0
    volumes:
      - ./setup:/mnt/setup:ro
    env_file: 
      - ./env/.env.local
    restart: "on-failure"

    
