version: "3"

network:
  net:

volumes:
  install:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - net
    restart: "always"
    
