version: "3"

services:
  ubuntu-web:
    # image:  "yen3/ubuntu-novnc"
    # image: "terrychu/docker-ubuntu-novnc"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 6080:6080
      - 3399:3390
      - 80:80
    # restart: "always"
